-- AlterTable
ALTER TABLE "AuditLogEntry" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Collection" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "CollectionSlug" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Comment" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "ContentTarget" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Follow" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "FollowTarget" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Like" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Lore" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "LoreSlug" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Post" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Realm" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "RealmSlug" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "RepresentationLore" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "UserAuth" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "UserProfile" ALTER COLUMN "id" DROP DEFAULT;
